import React, { useEffect, useState } from 'react'
import Loading from '../pages/Loading'
import { useAppContext } from '../context/AppContext'
import toast from 'react-hot-toast'

const Community = () => {

  const [images, setImages] = useState([])
  const [loading, setLoading] = useState(true)
  const { axios } = useAppContext()

  const fetchImages = async () => {
    try {
      const { data } = await axios.get('/api/user/published-images')
      if (data.success) {
        setImages(data.images)
      }
      else {
        toast.error(data.message)
      }
    } catch (error) {
      toast.error(error.message)
    }
    setLoading(false)
  }

  useEffect(() => {
    fetchImages()
  }, [])

  if (loading) return <Loading />

  return (
    <div className='w-full h-full overflow-y-auto p-6 md:p-10 xl:p-14'>
      <div className='mb-10'>
        <h2 className='text-3xl font-bold text-gray-800 dark:text-white mb-2'>Community Gallery</h2>
        <p className='text-sm text-gray-500 dark:text-gray-400'>Discover and draw inspiration from images generated by our community.</p>
      </div>

      {
        images.length > 0 ? (
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6 pb-12'>
            {
              images.map((item, index) => (
                <div key={index} className='group relative aspect-square rounded-2xl overflow-hidden border border-gray-200 dark:border-white/10 shadow-sm hover:shadow-2xl hover:shadow-primary/20 transition-all duration-500 hover:-translate-y-1'>
                  <img src={item.imageUrl} alt={`Generated by ${item.userName}`} className='w-full h-full object-cover transition-transform duration-700 group-hover:scale-110' loading="lazy" />

                  <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4'>
                    <div className='flex items-center justify-between gap-2'>
                      <div className='flex flex-col'>
                        <span className='text-[10px] uppercase tracking-wider text-white/60 font-medium'>Created By</span>
                        <span className='text-sm text-white font-semibold truncate'>{item.userName}</span>
                      </div>
                      <a
                        href={item.imageUrl}
                        target='_blank'
                        rel="noopener noreferrer"
                        aria-label="View full image"
                        className='p-2 bg-white/20 backdrop-blur-md rounded-lg hover:bg-white/40 transition-colors'>
                        <svg className='w-5 h-5 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path strokeLinecap='round' strokeLinejoin='round' strokeWidth='2' d='M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14'></path></svg>
                      </a>
                    </div>
                  </div>
                </div>
              ))
            }
          </div>
        ) : (
          <div className='h-[60vh] flex flex-col items-center justify-center text-center p-6'>
            <div className='w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-4'>
              <svg className='w-8 h-8 text-primary' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path strokeLinecap='round' strokeLinejoin='round' strokeWidth='2' d='M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z'></path></svg>
            </div>
            <p className='text-lg font-semibold text-gray-800 dark:text-white'>No images yet</p>
            <p className='text-sm text-gray-500 dark:text-gray-400 mt-1 max-w-xs'>Be the first to publish a masterpiece to our community gallery!</p>
          </div>
        )
      }
    </div>
  )
}

export default Community
